spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gestionstock?createDatabaseIfNotExist=true&userSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver


  ## Specifier SGBD
  jpa:
    database: MYSQL
    show-sql: false
    properties:
      hibernate:
        ejb:
          interceptor: com.khay.gestiondestock.interceptor.Interceptor
  # Hibernate DDL Auto (create, create-drop, update)
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


server:
  port: 8081

flickr:
  apiKey: ba8d75eedbce6b8d56b12ce9584b6f2e
  apiSecret: 3886a019cef03457
  appKey: 72157720862939557-31f778bdf8de866b
  appSecret: 2a3c65a8847a1534